local harpoon = require 'harpoon'

-- REQUIRED
harpoon:setup()
-- REQUIRED
--
vim.keymap.set('n', '<leader>a', function()
  harpoon:list():add()
end, { desc = '[A]dd file to Harpoon' })
vim.keymap.set('n', '<C-e>', function()
  harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = 'Harpoon quick menu' })

vim.keymap.set('n', '<C-1>', function()
  harpoon:list():select(1)
end)
vim.keymap.set('n', '<C-2>', function()
  harpoon:list():select(2)
end)
vim.keymap.set('n', '<C-3>', function()
  harpoon:list():select(3)
end)
vim.keymap.set('n', '<C-4>', function()
  harpoon:list():select(4)
end)
vim.keymap.set('n', '<C-5>', function()
  harpoon:list():select(5)
end)
vim.keymap.set('n', '<C-6>', function()
  harpoon:list():select(6)
end)
vim.keymap.set('n', '<C-7>', function()
  harpoon:list():select(7)
end)
vim.keymap.set('n', '<C-8>', function()
  harpoon:list():select(8)
end)

-- Toggle previous & next buffers stored within Harpoon list
vim.keymap.set('n', '<M-P>', function()
  harpoon:list():prev()
end)
vim.keymap.set('n', '<M-N>', function()
  harpoon:list():next()
end)
